### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Terrycoco** [jcolemorrison/react-dnd-redux-example#1]
After cloning, I ran npm install and I get the following errors:

npm WARN Invalid name: "React Dnd and Redux Simple Example"
npm WARN react-dnd-redux-example No description
npm WARN react-dnd-redux-example No repository field.
npm WARN react-dnd-redux-example No README data
npm WARN react-dnd-redux-example No license field.

So it fails to install the packages.

You need to change the name to have no spaces ie  ReactDndWithRedux

**Comment by jcolemorrison** [comment]
good catch!  I went ahead and changed it.  Thanks a ton of the heads up!
